// Statistical helpers for digit-based market analysis.
// NOTE: Deriv synthetic indices are generated by a verified random number
// generator. These stats describe recent frequency, not a guaranteed outcome.

export function digitDistribution(ticks) {
  const counts = Array(10).fill(0);
  ticks.forEach((t) => {
    counts[t.digit] += 1;
  });
  const total = ticks.length || 1;
  return counts.map((c, digit) => ({
    digit,
    count: c,
    pct: (c / total) * 100,
  }));
}

export function buildStats(ticks) {
  const dist = digitDistribution(ticks);
  const total = ticks.length;
  const sorted = [...dist].sort((a, b) => b.count - a.count);
  const hot = sorted[0] || { digit: 0, pct: 0 };
  const cold = sorted[sorted.length - 1] || { digit: 0, pct: 0 };

  let odd = 0;
  let even = 0;
  let over = 0; // 6-9
  let under = 0; // 0-4
  let equalFive = 0;

  ticks.forEach((t) => {
    if (t.digit % 2 === 0) even += 1;
    else odd += 1;
    if (t.digit > 5) over += 1;
    else if (t.digit < 5) under += 1;
    else equalFive += 1;
  });

  const pct = (n) => (total ? (n / total) * 100 : 0);

  return {
    dist,
    total,
    hot,
    cold,
    odd: pct(odd),
    even: pct(even),
    over: pct(over),
    under: pct(under + equalFive * 0), // over 5 strictly means 6-9; under/equal handled separately
    equalFive: pct(equalFive),
    underOrEqual: pct(under + equalFive),
    oddCount: odd,
    evenCount: even,
  };
}

export function buildPredictions(stats) {
  const { hot, cold, odd, even, over, underOrEqual } = stats;

  const matches = {
    digit: hot.digit,
    confidence: hot.pct,
  };

  const differs = {
    digit: cold.digit,
    confidence: 100 - cold.pct,
  };

  const overUnder =
    over >= underOrEqual
      ? { pick: "OVER 4", confidence: over }
      : { pick: "UNDER 5", confidence: underOrEqual };

  const oddEven =
    odd >= even
      ? { pick: "ODD", confidence: odd }
      : { pick: "EVEN", confidence: even };

  return { matches, differs, overUnder, oddEven };
}
